# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_scsi"
    "ahci"
    "sd_mod"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/feaaabf1-d1b6-48b7-874d-9dd0f1f7f353";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/8edd0f83-5500-463d-8fd7-ca5b0c945437"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
